In [251]:
from collections import Counter
import numpy as np

In [252]:
'''语料'''
corpus  = "她的菜很好,她的菜很香,他的她很好,他的菜很香,他的她很好,很香的菜,很好的她,很菜的他,她的好,菜的香,他的菜,她很好,他很菜,菜很好"
corpus = corpus.split(',')

In [253]:
'''语料预处理'''
counter = Counter()
for sentence in corpus:
    for word in sentence:
        counter[word] += 1
counter = counter.most_common() #按照由大到小顺序返回前n个数据
l = len(counter)
word2id = {counter[i][0]:i for i in range(l)} #字典数据类型构建word2id
id2word = {i :counter[i][0] for i in range(l)} #字典数据类型构建id2word
print(counter)
print(word2id)
print(id2word)

[('的', 11), ('很', 11), ('菜', 9), ('她', 7), ('好', 7), ('他', 6), ('香', 4)]
{'的': 0, '很': 1, '菜': 2, '她': 3, '好': 4, '他': 5, '香': 6}
{0: '的', 1: '很', 2: '菜', 3: '她', 4: '好', 5: '他', 6: '香'}


In [254]:
'''N-gram模型训练'''
l = len(counter) #counter的长度，即词的个数
S = sum(counter[i][1] for i in range(l))
unigram = np.array([counter[i][1] for i in range(l)])/ S #1-gram
print(unigram)

for sentence in corpus:
#     print (sentence)
    print (np.array([word2id[word] for word in sentence]))#句子的id表示
    
bigram = np.zeros((l,l))
for sentence in corpus:
    for i in range(1,len(sentence)):
        bigram[word2id[sentence[i-1]],word2id[sentence[i]]] += 1 #2-gram
print(bigram)

[0.2        0.2        0.16363636 0.12727273 0.12727273 0.10909091
 0.07272727]
[3 0 2 1 4]
[3 0 2 1 6]
[5 0 3 1 4]
[5 0 2 1 6]
[5 0 3 1 4]
[1 6 0 2]
[1 4 0 3]
[1 2 0 5]
[3 0 4]
[2 0 6]
[5 0 2]
[3 1 4]
[5 1 2]
[2 1 4]
[[0. 0. 5. 3. 1. 1. 1.]
 [0. 0. 2. 0. 6. 0. 3.]
 [2. 4. 0. 0. 0. 0. 0.]
 [3. 3. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [4. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]


#对unigram解释

# 对bigram解释 

In [255]:
'''句子概率'''
def prob_1(sentence): #1-gram预测
    sentence_list1 = [word2id[i] for i in sentence]
    p = 0
    for i in range(len(sentence_list1)):
        p += unigram[sentence_list1[i]]
    return p

def prob_2(sentence):#2-gram预测
    sentence_list2 = [word2id[i] for i in sentence]
    p = 0
    for i in range(1,len(sentence_list2)):
        p += bigram[sentence_list2[i-1],sentence_list2[i]]
    return p

In [267]:
'''实际预测'''
P1 = prob_1("香")
P2 = prob_2("的的")
print(P1,P2)

0.07272727272727272 0.0
